package ru.mirea.edu.dormitorybot.statemachine;

public enum State {
    MAIN_MENU,
    SEND_SCHEDULE_PHOTO,
    APPROVE_SCHEDULE_UPDATE,
    CHOOSE_EMPLOYEE,
    INPUT_NEWSLETTER_TEXT,
    APPROVE_NEWSLETTER,
    ADD_ADMIN,
    DELETE_ADMIN,
    ADMIN_MENU,
    EDIT_EMPLOYEE,
    WAITING_NEWSLETTER;
}
