version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - '8080:8080'
    networks:
      - backend

  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - backend
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=EGOR
      - MINIO_ROOT_PASSWORD=EGOR_VORONIN

networks:
  backend:
    driver: bridge

volumes:
  minio_data:
    driver: local