app:
  access-token: vk1.a.fT7f19HLuh_SgADuSM8Cfj_2CUGE3kmENVRbJZZ74EiEl96V-2_LD9aaCIlk4KC9ahO6QkCBG_fi7eiUks6PBJPJH1QUOLvi5XAFy4eOqHLpjgjATt3_xZodbYHJuNgK2YS4QjFuB9gIHa3s539pTOvIkej1QCl8AWU0QiZvG7X7nDcLB9BplJY8YpfcLPrslzZDdisJ_j1kCbBEv7SfMw

minio:
  bucket: schedule
  url: http://localhost:9000
  access_key: minioadmin
  secret_key: minioadmin